version: 2
updates:

  # GHA
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    labels:
      - type:github_actions

  # Javascript
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 15
    labels:
      - type:dependencies
