changelog:

  exclude:
    authors:
      - dependabot
      - dependabot[bot]

  categories:
    - title: Security Fixes
      labels:
        - type:security

    - title: New Features
      labels:
        - type:enhancement

    - title: Accessibility
      labels:
        - type:usability
        - type:accessibility
        - type:visual-clarity

    - title: Bug Fixes
      labels:
        - type:bug

    - title: Documentation
      labels:
        - type:documentation

    - title: Typing
      labels:
        - type:typing

    - title: Code Enhancements
      labels:
        - type:code-enhancement
        - type:tests

    - title: Maintenance and Dependencies
      labels:
        - type:dependencies
        - type:github_actions
        - type:infrastructure

    - title: Other Changes
      labels:
        - "*"
