project_id: 568833
api_token_env: CROWDIN_TOKEN
base_path: .
preserve_hierarchy: true

files:
  - source: '/src/i18n/org/opencastproject/adminui/languages/lang-en_US.json'
    translation: '/src/i18n/org/opencastproject/adminui/languages/lang-%locale_with_underscore%.json'
