name: Build » Container image

on:
  push:
    branches-ignore:
      - 'dependabot/**'
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  container-image-build:
    runs-on: ubuntu-latest
    steps:
      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build image
        uses: docker/build-push-action@v7
        with:
          push: false # This is handled in another workflow!
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=docker,dest=${{ runner.temp }}/build.tar

      - name: Upload docker image to GHA artifacts
        uses: actions/upload-artifact@v7
        with:
          name: ${{ github.run_id }}-image
          path: ${{ runner.temp }}/build.tar

      # This is stupid, but GHA currently zeros out the pull_requests list in forked repos
      # so we have no way to get at this number without going through PRs and matching via hash
      - name: Save PR Number to disk
        run: echo "${{ github.event.number }}" > pr_number.txt

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ github.run_id }}-number
          path: pr_number.txt
